26 implement substitution alternative
ourstudio-se/puan-rust pull request #27
Opened 2022-11-07 12:47 UTC by znittzel

2022-11-07 13:49 UTC, ourmoa requested changes

2022-11-07 13:49 UTC, ourmoa commented on src/lib.rs
> +impl PartialEq for Variable {
More descriptive function name? 
```suggestion
impl IdEq for Variable {
```

2022-11-07 13:49 UTC, ourmoa commented on src/lib.rs
> +        // 2: 5 + 6 >= 5 (5 has bounds (-3,3), 6 is bool)
```suggestion
        // 2: 5 + 6 >= 4 (5 has bounds (-3,3), 6 is bool) 
```

2022-11-07 14:42 UTC, znittzel commented on src/lib.rs
> +impl PartialEq for Variable {
Isn't PartialEq a Trait?

2022-11-08 13:10 UTC, ourmoa requested changes

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
>  use itertools::iproduct;
```suggestion
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +use std::ops::Range;
```suggestion
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +use itertools::Itertools;
```suggestion
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +    /// will be merged into this constraint. If requirements is not met, then `to_lineq_extended` is called.
```suggestion
    /// will be merged into this constraint. If the requirements are not met, then `to_lineq_extended` is called. 
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +/// A `Statement` is a declaration of a expression (or proposition) connected to a `Variable`.
```suggestion
/// A `Statement` is a declaration of an expression (or proposition) connected to a `Variable`.
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +    // All bottom / atomic variable ids. E.i. statements that don't have any children.
```suggestion
    // All bottom / atomic variable ids, e.i. statements that don't have any children.
```

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +    // `all_relation` how the results from lineqs0 and lineqs1 relates. If `all_relation` is true then either both
feels like something is missing in the last sentence?

2022-11-08 13:10 UTC, ourmoa commented on src/lib.rs
> +        assert!(validate_theory_lineqs(t, actual, expected));
I believe we want to validate the theory based on the input and actual and not on the expected

2022-11-09 06:04 UTC, ourmoa requested changes

2022-11-09 06:04 UTC, ourmoa commented on src/lib.rs
> +    /// ```
```suggestion
```
Remove?

2022-11-09 06:04 UTC, ourmoa commented on src/lib.rs
> +    // Validates all combinations generated from `variable_bounds` in two vectors, lineqs0 och lineqs1, of GeLineq data types.
```suggestion
    // Validates that all combinations, generated from `variable_bounds`, in two vectors of GeLineqs gives the same result, i.e. they hold the same truth table```

2022-11-09 06:04 UTC, ourmoa commented on src/lib.rs
> +    // `all_relation` how the results from lineqs0 and lineqs1 relates. If `all_relation` is true then either both
```suggestion
    // The `all_relation` states how the GeLineq within each vector relates. If `all_relation` is true then all GeLineqs of the vector must hold to produce `True` as output. If `all_relation` is false then it is treated as an any, and only one GeLineq of the vector must hold to produce `True` as output. 
```

2022-11-09 09:04 UTC, ourmoa approved these changes

2022-11-09 09:04 UTC, merged